baseURL: 'https://kanatonishiura.com/'
languageCode: en-us
title: Kanato Nishiura
theme: PaperMod

googleAnalytics: G-WZV80VBNE5

assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"

editPost:
    URL: "https://github.com/xknt21/mypage/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true 

params:
  cover:
      linkFullImages: true
      hideInList: false
      hiddenInSingle: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  hideDescriptionInList: false
  socialIcons:
          - name: instagram
            url: "https://instagram.com/kanato_0821"
          - name: github
            url: "https://github.com/xknt21"

  contentDir: content/en/blogs/
  staticDir: static/
  publishDir: "data"
  profileMode:
      enabled: true
      title: Hello world, I'm kanato! 🧑🏻‍💻
      subtitle: "Welcome to my digital garden where I document my learnings as a Uni student."
      imageUrl: "img_6710-2.jpg"
      imageWidth: 120
      imageHeight: 120
      imageTitle: kanato-profile
      
      buttons:
        - name: About Me
          url: /about
        - name: Blog
          url: /blogs

      fuseOpts:
         isCaseSensitive: false
         shouldSort: true
         location: 0
         distance: 1000
         threshold: 0.4
         minMatchCharLength: 0
         keys: ["title", "permalink", "summary", "content"]
menu:
   main:
     - identifier: About Me
       name: About Me
       url: /about
       weight: 5
     - identifier: Blog
       name: Blog
       url: /blogs
       weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup: 
   goldmark:
       renderer:
          unsafe: true
