build:
  publish: public
  command: hugo --gc --minify
  environment:
    HUGO_VERSION: 0.121.1
context:
  production:
    environment:
      HUGO_VERSION: 0.121.1
      HUGO_ENV: production
      HUGO_ENABLEGITINFO: 'true'
  split1:
    command: hugo --gc --minify --enableGitInfo
    environment:
      HUGO_ENV: production
  deploy-preview:
    command: hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
    environment:
      HUGO_VERSION: 0.121.1
  branch-deploy:
    command: hugo --gc --minify -b $DEPLOY_PRIME_URL
  next:
    environment:
      HUGO_ENABLEGITINFO: 'true'
redirects:
  - from: /public/*
    to: /public/
    status: 200
